[
  ./acme.nix
  # ./ai.nix
  ./auto-update.nix
  ./chatwick.nix
  ./desktop.nix
  ./domains.nix
  ./dynamic-dns.nix
  ./factorio-server.nix
  ./file-share.nix
  ./gaming.nix
  ./gateway.nix
  ./gpu-amd.nix
  ./gpu-nvidia.nix
  ./hostname.nix
  ./jellyfin.nix
  ./livestream-server.nix
  ./mc-quick.nix
  ./mount-9p.nix
  ./nginx.nix
  ./protonvpn.nix
  ./quilt-server.nix
  ./vault.nix
  ./virtualisation.nix
]
