[
  ./acme.nix
  ./auto-update.nix
  ./desktop.nix
  ./domains.nix
  ./dynamic-dns.nix
  ./factorio-server.nix
  ./gaming.nix
  ./gateway.nix
  ./gpu-amd.nix
  ./hostname.nix
  ./livestream-server.nix
  ./nginx.nix
  ./quilt-server.nix
  ./vault.nix
]
