keys:
  - &dane_fishtank age1wnvhthprrmq2w4u2w8l3jshcrejdzqsc2elvdlc6ml7tupa27qyqswg3n8
  - &dane_bludgeonder age1mg25snt8p559cqh4zlsc7ef8zu56kqmpw97yhdnhag7ajweasskst4ehr8
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *dane_fishtank
        - *dane_bludgeonder
