name = "Fabric Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c6b2850c8a5ab68ebdfeaa8edb5e19f29edc154faeaa623dd19d31ec2c68c70"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
